# Generated by Django 3.0.12 on 2021-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_discount',
            field=models.IntegerField(help_text='User discount', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
