# Generated by Django 3.0.12 on 2021-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210205_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_discount',
            field=models.IntegerField(default=0, help_text='User discount', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
