# Generated by Django 3.0.12 on 2021-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210211_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='', help_text='User phone', max_length=20, null=True),
        ),
    ]
