# Generated by Django 3.1.6 on 2021-02-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtogazkomplect', '0002_auto_20210218_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(default='', max_length=100, verbose_name='Наименование фотографии'),
        ),
    ]
