# Generated by Django 3.1.6 on 2021-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtogazkomplect', '0007_auto_20210218_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
    ]
