# Generated by Django 3.1.6 on 2021-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtogazkomplect', '0008_auto_20210218_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Заголовок'),
        ),
    ]
